use serde_json::Value;

use super::{NoteBlockUpdate, NoteBlockWrite};

struct NoteBlockPayloadRefs<'a> {
    paragraph: Option<&'a Value>,
    heading_1: Option<&'a Value>,
    heading_2: Option<&'a Value>,
    heading_3: Option<&'a Value>,
    heading_4: Option<&'a Value>,
    heading_5: Option<&'a Value>,
    heading_6: Option<&'a Value>,
    bulleted_list_item: Option<&'a Value>,
    numbered_list_item: Option<&'a Value>,
    to_do: Option<&'a Value>,
    toggle: Option<&'a Value>,
    callout: Option<&'a Value>,
    quote: Option<&'a Value>,
    child_page: Option<&'a Value>,
    child_database: Option<&'a Value>,
    breadcrumb: Option<&'a Value>,
    table_of_contents: Option<&'a Value>,
    column_list: Option<&'a Value>,
    column: Option<&'a Value>,
    table: Option<&'a Value>,
    table_row: Option<&'a Value>,
    tab: Option<&'a Value>,
    image: Option<&'a Value>,
    video: Option<&'a Value>,
    audio: Option<&'a Value>,
    file: Option<&'a Value>,
    pdf: Option<&'a Value>,
    bookmark: Option<&'a Value>,
    link_preview: Option<&'a Value>,
    synced_block: Option<&'a Value>,
    template: Option<&'a Value>,
    button: Option<&'a Value>,
    embed: Option<&'a Value>,
    equation: Option<&'a Value>,
    divider: Option<&'a Value>,
    code: Option<&'a Value>,
    unsupported: Option<&'a Value>,
}

impl<'a> NoteBlockPayloadRefs<'a> {
    fn from_write(block: &'a NoteBlockWrite) -> Self {
        Self {
            paragraph: block.paragraph.as_ref(),
            heading_1: block.heading_1.as_ref(),
            heading_2: block.heading_2.as_ref(),
            heading_3: block.heading_3.as_ref(),
            heading_4: block.heading_4.as_ref(),
            heading_5: block.heading_5.as_ref(),
            heading_6: block.heading_6.as_ref(),
            bulleted_list_item: block.bulleted_list_item.as_ref(),
            numbered_list_item: block.numbered_list_item.as_ref(),
            to_do: block.to_do.as_ref(),
            toggle: block.toggle.as_ref(),
            callout: block.callout.as_ref(),
            quote: block.quote.as_ref(),
            child_page: block.child_page.as_ref(),
            child_database: block.child_database.as_ref(),
            breadcrumb: block.breadcrumb.as_ref(),
            table_of_contents: block.table_of_contents.as_ref(),
            column_list: block.column_list.as_ref(),
            column: block.column.as_ref(),
            table: block.table.as_ref(),
            table_row: block.table_row.as_ref(),
            tab: block.tab.as_ref(),
            image: block.image.as_ref(),
            video: block.video.as_ref(),
            audio: block.audio.as_ref(),
            file: block.file.as_ref(),
            pdf: block.pdf.as_ref(),
            bookmark: block.bookmark.as_ref(),
            link_preview: block.link_preview.as_ref(),
            synced_block: block.synced_block.as_ref(),
            template: block.template.as_ref(),
            button: block.button.as_ref(),
            embed: block.embed.as_ref(),
            equation: block.equation.as_ref(),
            divider: block.divider.as_ref(),
            code: block.code.as_ref(),
            unsupported: block.unsupported.as_ref(),
        }
    }

    fn from_update(update: &'a NoteBlockUpdate) -> Self {
        Self {
            paragraph: update.paragraph.as_ref(),
            heading_1: update.heading_1.as_ref(),
            heading_2: update.heading_2.as_ref(),
            heading_3: update.heading_3.as_ref(),
            heading_4: update.heading_4.as_ref(),
            heading_5: update.heading_5.as_ref(),
            heading_6: update.heading_6.as_ref(),
            bulleted_list_item: update.bulleted_list_item.as_ref(),
            numbered_list_item: update.numbered_list_item.as_ref(),
            to_do: update.to_do.as_ref(),
            toggle: update.toggle.as_ref(),
            callout: update.callout.as_ref(),
            quote: update.quote.as_ref(),
            child_page: update.child_page.as_ref(),
            child_database: update.child_database.as_ref(),
            breadcrumb: update.breadcrumb.as_ref(),
            table_of_contents: update.table_of_contents.as_ref(),
            column_list: update.column_list.as_ref(),
            column: update.column.as_ref(),
            table: update.table.as_ref(),
            table_row: update.table_row.as_ref(),
            tab: update.tab.as_ref(),
            image: update.image.as_ref(),
            video: update.video.as_ref(),
            audio: update.audio.as_ref(),
            file: update.file.as_ref(),
            pdf: update.pdf.as_ref(),
            bookmark: update.bookmark.as_ref(),
            link_preview: update.link_preview.as_ref(),
            synced_block: update.synced_block.as_ref(),
            template: update.template.as_ref(),
            button: update.button.as_ref(),
            embed: update.embed.as_ref(),
            equation: update.equation.as_ref(),
            divider: update.divider.as_ref(),
            code: update.code.as_ref(),
            unsupported: update.unsupported.as_ref(),
        }
    }

    fn get(&self, block_type: &str) -> Option<&'a Value> {
        match block_type {
            "paragraph" => self.paragraph,
            "heading_1" => self.heading_1,
            "heading_2" => self.heading_2,
            "heading_3" => self.heading_3,
            "heading_4" => self.heading_4,
            "heading_5" => self.heading_5,
            "heading_6" => self.heading_6,
            "bulleted_list_item" => self.bulleted_list_item,
            "numbered_list_item" => self.numbered_list_item,
            "to_do" => self.to_do,
            "toggle" => self.toggle,
            "callout" => self.callout,
            "quote" => self.quote,
            "child_page" => self.child_page,
            "child_database" => self.child_database,
            "breadcrumb" => self.breadcrumb,
            "table_of_contents" => self.table_of_contents,
            "column_list" => self.column_list,
            "column" => self.column,
            "table" => self.table,
            "table_row" => self.table_row,
            "tab" => self.tab,
            "image" => self.image,
            "video" => self.video,
            "audio" => self.audio,
            "file" => self.file,
            "pdf" => self.pdf,
            "bookmark" => self.bookmark,
            "link_preview" => self.link_preview,
            "synced_block" => self.synced_block,
            "template" => self.template,
            "button" => self.button,
            "embed" => self.embed,
            "equation" => self.equation,
            "divider" => self.divider,
            "code" => self.code,
            "unsupported" => self.unsupported,
            _ => None,
        }
    }
}

pub(super) fn payload_from_write(block: &NoteBlockWrite) -> Option<&Value> {
    NoteBlockPayloadRefs::from_write(block).get(&block.block_type)
}

pub(super) fn payload_from_update<'a>(
    update: &'a NoteBlockUpdate,
    block_type: &str,
) -> Option<&'a Value> {
    NoteBlockPayloadRefs::from_update(update).get(block_type)
}
