import type { ChatFileIconId } from "./file-icons.generated";

export interface ChatFilePresentation {
  icon: ChatFileIconId;
  darkIcon?: ChatFileIconId;
}

const EXACT_FILE_ICONS: Readonly<Record<string, ChatFileIconId>> = {
  ".ansible-lint": "ansible",
  ".babelrc": "babel",
  ".bazelrc": "bazel",
  ".dockerignore": "docker",
  ".editorconfig": "editorconfig",
  ".eslintignore": "eslint",
  ".eslintrc": "eslint",
  ".gitattributes": "git",
  ".gitconfig": "git",
  ".gitignore": "git",
  ".gitlab-ci.yml": "gitlab",
  ".gitmodules": "git",
  ".node-version": "node",
  ".npmrc": "npm",
  ".nvmrc": "node",
  ".parcelrc": "parcel",
  ".prettierignore": "prettier",
  ".prettierrc": "prettier",
  ".python-version": "python",
  ".ruby-version": "ruby",
  ".stylelintignore": "stylelint",
  ".stylelintrc": "stylelint",
  ".terraform.lock.hcl": "terraform",
  ".yarnrc": "yarn",
  "agents.md": "agents",
  "angular.json": "angular",
  "biome.json": "biome",
  "biome.jsonc": "biome",
  "brewfile": "brew",
  "build": "bazel",
  "build.bazel": "bazel",
  "build.gradle": "gradle",
  "build.gradle.kts": "gradle",
  "build.ninja": "ninja",
  "build.zig": "zig",
  "bun.lock": "bun",
  "bun.lockb": "bun",
  "cargo.lock": "cargo",
  "cargo.toml": "cargo",
  "chart.yaml": "helm",
  "claude.md": "claude",
  "cmakelists.txt": "cmake",
  "codeowners": "codeowners",
  "components.json": "shadcn",
  "composer.json": "composer",
  "composer.lock": "composer",
  "compose.yaml": "docker",
  "compose.yml": "docker",
  "deno.json": "deno",
  "deno.jsonc": "deno",
  "deno.lock": "deno",
  "docker-compose.yaml": "docker",
  "docker-compose.yml": "docker",
  "dockerfile": "docker",
  "flake.lock": "nix",
  "flake.nix": "nix",
  "gemfile": "bundler",
  "gemfile.lock": "bundler",
  "go.mod": "go-package",
  "go.sum": "go-package",
  "go.work": "go-package",
  "go.work.sum": "go-package",
  "gradle.properties": "gradle",
  "gradlew": "gradle",
  "gradlew.bat": "gradle",
  "jenkinsfile": "jenkins",
  "justfile": "just",
  "lerna.json": "package",
  "makefile": "gnu",
  "mix.exs": "elixir",
  "mix.lock": "elixir",
  "module.bazel": "bazel",
  "netlify.toml": "netlify",
  "nx.json": "nx",
  "npm-shrinkwrap.json": "npm",
  "package-lock.json": "npm",
  "package.json": "node",
  "package.swift": "swift",
  "pipfile": "python",
  "pipfile.lock": "python",
  "pnpm-lock.yaml": "pnpm",
  "pnpm-workspace.yaml": "pnpm",
  "poetry.lock": "python",
  "pom.xml": "maven",
  "procfile": "procfile",
  "pubspec.lock": "dart",
  "pubspec.yaml": "dart",
  "pyproject.toml": "python",
  "pytest.ini": "python",
  "requirements.txt": "python",
  "rust-toolchain": "rust",
  "rust-toolchain.toml": "rust",
  "rustfmt.toml": "rust",
  "settings.gradle": "gradle",
  "settings.gradle.kts": "gradle",
  "tauri.conf.json": "tauri",
  "turbo.json": "turbo",
  "vagrantfile": "vagrant",
  "vercel.json": "vercel",
  "workspace": "bazel",
  "workspace.bazel": "bazel",
  "wrangler.json": "cloudflare",
  "wrangler.jsonc": "cloudflare",
  "wrangler.toml": "cloudflare",
  "yarn.lock": "yarn"
};

const CONFIG_STEM_ICONS = [
  ["astro.config", "astro"],
  ["babel.config", "babel"],
  ["cypress.config", "cypress"],
  ["drizzle.config", "database"],
  ["electron-builder", "electron"],
  ["esbuild.config", "esbuild"],
  ["eslint.config", "eslint"],
  ["jest.config", "jest"],
  ["next.config", "next"],
  ["nuxt.config", "nuxt"],
  ["parcel.config", "parcel"],
  ["playwright.config", "playwright"],
  ["postcss.config", "postcss"],
  ["prettier.config", "prettier"],
  ["rollup.config", "rollup"],
  ["stylelint.config", "stylelint"],
  ["svelte.config", "svelte"],
  ["tailwind.config", "tailwind"],
  ["vite.config", "vite"],
  ["vitest.config", "vitest"],
  ["webpack.config", "webpack"]
] as const satisfies readonly (readonly [string, ChatFileIconId])[];

const EXTENSION_ICONS: Readonly<Record<string, ChatFileIconId>> = {
  "7z": "zip",
  aac: "audio",
  adoc: "markdown",
  aiff: "audio",
  ansible: "ansible",
  asm: "assembly",
  astro: "astro",
  avi: "video",
  avif: "image",
  bash: "shell",
  bat: "shell",
  bib: "tex",
  bmp: "image",
  bz2: "zip",
  bzl: "bazel",
  c: "c",
  cc: "cpp",
  cfg: "config",
  cjs: "javascript",
  cbl: "cobol",
  clj: "clojure",
  cljc: "clojure",
  cljs: "clojure",
  cmake: "cmake",
  cob: "cobol",
  coffee: "coffeescript",
  conf: "config",
  cpp: "cpp",
  cr: "crystal",
  cs: "csharp",
  cshtml: "razor",
  csproj: "csharp",
  css: "css",
  cson: "coffeescript",
  csv: "text",
  cts: "typescript",
  cxx: "cpp",
  d: "dlang",
  dart: "dart",
  db: "database",
  dll: "default",
  doc: "word",
  docx: "word",
  dpr: "delphi",
  ejs: "html",
  elm: "elm",
  edn: "clojure",
  eot: "font",
  erl: "erlang",
  ex: "elixir",
  exe: "default",
  exs: "elixir",
  f: "fortran",
  f77: "fortran",
  f90: "fortran",
  f95: "fortran",
  fish: "shell",
  flac: "audio",
  fs: "fsharp",
  fsi: "fsharp",
  fsproj: "fsharp",
  fsx: "fsharp",
  gif: "image",
  gd: "godot",
  go: "go",
  gql: "graphql",
  gradle: "gradle",
  graphql: "graphql",
  groovy: "groovy",
  gsh: "groovy",
  gvy: "groovy",
  gz: "zip",
  h: "c",
  handlebars: "handlebars",
  haml: "html",
  hbs: "handlebars",
  hcl: "terraform",
  hh: "cpp",
  hpp: "cpp",
  htm: "html",
  html: "html",
  hxx: "cpp",
  hx: "haxe",
  hxml: "haxe",
  iced: "coffeescript",
  ico: "favicon",
  ini: "config",
  ipynb: "jupyter",
  jar: "java",
  java: "java",
  jpeg: "image",
  jpg: "image",
  js: "javascript",
  json: "json",
  json5: "json",
  jsonc: "json",
  jsx: "react",
  jl: "julia",
  jinja: "jinja",
  jinja2: "jinja",
  kt: "kotlin",
  kts: "kotlin",
  less: "less",
  lhs: "haskell",
  liquid: "liquid",
  log: "log",
  lua: "lua",
  m4a: "audio",
  m: "objectivec",
  mat: "matlab",
  md: "markdown",
  mdx: "mdx",
  mjs: "javascript",
  mkv: "video",
  ml: "ocaml",
  mli: "ocaml",
  mov: "video",
  mustache: "handlebars",
  mm: "objectivec",
  mp3: "audio",
  mp4: "video",
  mts: "typescript",
  nix: "nix",
  nim: "nim",
  nimble: "nim",
  njk: "jinja",
  odp: "powerpoint",
  ods: "excel",
  odt: "word",
  ogg: "audio",
  otf: "font",
  pas: "delphi",
  pdf: "pdf",
  php: "php",
  phtml: "php",
  pl: "perl",
  pm: "perl",
  png: "image",
  pot: "powerpoint",
  potx: "powerpoint",
  pps: "powerpoint",
  ppsx: "powerpoint",
  ppt: "powerpoint",
  pptx: "powerpoint",
  pug: "pug",
  prisma: "prisma",
  properties: "config",
  proto: "protobuf",
  ps1: "powershell",
  psd1: "powershell",
  psm1: "powershell",
  py: "python",
  pyi: "python",
  pyw: "python",
  r: "r",
  rake: "ruby",
  rar: "zip",
  razor: "razor",
  rb: "ruby",
  rmd: "r",
  rs: "rust",
  rst: "markdown",
  sbt: "scala",
  sass: "sass",
  scala: "scala",
  scss: "sass",
  sh: "shell",
  s: "assembly",
  so: "default",
  sol: "solidity",
  sql: "sql",
  sqlite: "sqlite",
  sqlite3: "sqlite",
  svelte: "svelte",
  svg: "svg",
  sln: "csharp",
  styl: "stylus",
  swift: "swift",
  tar: "zip",
  tex: "tex",
  tf: "terraform",
  tfvars: "terraform",
  tgz: "zip",
  tif: "image",
  tiff: "image",
  toml: "toml",
  ts: "typescript",
  tsv: "text",
  tsx: "react",
  ttf: "font",
  txt: "text",
  vb: "vb",
  vbproj: "vb",
  vbs: "vb",
  vue: "vue",
  wasm: "wasm",
  wav: "audio",
  webm: "video",
  webmanifest: "json",
  webp: "image",
  woff: "font",
  woff2: "font",
  xls: "excel",
  xlsm: "excel",
  xlsx: "excel",
  xml: "xml",
  xsd: "xml",
  xsl: "xml",
  xslt: "xml",
  xz: "zip",
  yaml: "yaml",
  yml: "yaml",
  zig: "zig",
  zip: "zip",
  zsh: "shell"
};

const DARK_VARIANTS: Partial<Record<ChatFileIconId, ChatFileIconId>> = {
  next: "next-dark",
  rust: "rust-dark"
};

/**
 * Resolves a recognizable local icon for a workspace file.
 *
 * Exact filenames and tool configuration names take precedence over compound
 * suffixes and ordinary extensions. The comparison is case-insensitive.
 *
 * @param filePath Workspace-relative or absolute file path.
 * @returns Local sprite icon identifiers for the active color mode.
 */
export function chatFilePresentation(filePath: string): ChatFilePresentation {
  const normalizedPath = filePath.replaceAll("\\", "/").toLowerCase();
  const name = normalizedPath.split("/").at(-1) ?? normalizedPath;
  const exact = EXACT_FILE_ICONS[name];
  if (exact) return presentation(exact);

  const named = namedFileIcon(name);
  if (named) return presentation(named);

  for (const [stem, icon] of CONFIG_STEM_ICONS) {
    if (name === stem || name.startsWith(`${stem}.`)) return presentation(icon);
  }

  if (name.endsWith(".d.ts")) return presentation("typescript-definition");
  if (/\.(?:test|spec)\.tsx$/.test(name)) return presentation("react");
  if (/\.(?:test|spec)\.(?:ts|mts|cts)$/.test(name)) return presentation("typescript-test");
  if (/\.(?:test|spec)\.(?:js|mjs|cjs)$/.test(name)) return presentation("javascript-test");

  const extension = name.includes(".") ? name.split(".").at(-1) ?? "" : "";
  return presentation(EXTENSION_ICONS[extension] ?? "default");
}

function namedFileIcon(name: string): ChatFileIconId | undefined {
  if (name === "containerfile" || name.startsWith("dockerfile.")) return "docker";
  if (name === "license" || name === "licence" || /^licen[cs]e[._-]/.test(name)) return "license";
  if (name === "readme" || name.startsWith("readme.")) return "markdown";
  if (name === "changelog" || name.startsWith("changelog.")) return "markdown";
  if (name === ".env" || name.startsWith(".env.")) return "dotenv";
  if (name.startsWith("requirements") && name.endsWith(".txt")) return "python";
  if (name === "tsconfig.json" || name === "jsconfig.json" || /^tsconfig\..+\.json$/.test(name)) {
    return "typescript-config";
  }
  if (/^\.eslint(?:rc)?(?:\.|$)/.test(name)) return "eslint";
  if (/^\.prettier(?:rc)?(?:\.|$)/.test(name)) return "prettier";
  if (/^\.stylelint(?:rc)?(?:\.|$)/.test(name)) return "stylelint";
  if (name.endsWith(".lock")) return "package";
  return undefined;
}

function presentation(icon: ChatFileIconId): ChatFilePresentation {
  const darkIcon = DARK_VARIANTS[icon];
  return darkIcon ? { icon, darkIcon } : { icon };
}
