[package]
name = "ganbaru-native-messaging"
version = "0.1.5"
description = "Ganbaru AI Chromium native messaging host"
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
default-run = "ganbaru-ai-native-messaging"

[[bin]]
name = "ganbaru-ai-native-messaging"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
