use super::{
    BridgeBacklink, BridgeDatabaseView, BridgeOptions, BridgePage, BridgeProject, BridgeTask,
    EXPORT_VERSION, SCHEMA_VERSION,
};
use crate::models::{NoteAgentBridgeExportDiagnosticDto, NoteMarkdownExportRequest};
use crate::transfers;
use crate::transfers::markdown_export::format::{escape_inline, escape_link_label};
use sqlx::SqlitePool;
use std::collections::BTreeMap;

pub(super) async fn render_bridge_markdown(
    pool: &SqlitePool,
    pages: &[BridgePage],
    database_views: &[BridgeDatabaseView],
    projects: &[BridgeProject],
    backlinks: &[BridgeBacklink],
    options: BridgeOptions,
    diagnostics: &mut Vec<NoteAgentBridgeExportDiagnosticDto>,
) -> Result<String, String> {
    let mut markdown = String::new();
    markdown.push_str("# Ganbaru AI agent bridge export\n\n");
    markdown.push_str("> Derivative markdown view generated from Ganbaru AI SQLite. Do not edit this file as source of truth. Recreate it from Ganbaru AI after canonical data changes.\n\n");
    markdown.push_str("## Export metadata\n\n");
    markdown.push_str(&format!("- Schema: `{SCHEMA_VERSION}`\n"));
    markdown.push_str(&format!("- Export version: `{EXPORT_VERSION}`\n"));
    markdown.push_str(&format!("- Notes pages: `{}`\n", pages.len()));
    markdown.push_str(&format!("- Projects: `{}`\n", projects.len()));
    markdown.push_str(&format!("- Database views: `{}`\n", database_views.len()));
    markdown.push_str(&format!("- Backlinks: `{}`\n", backlinks.len()));
    markdown.push_str(&format!(
        "- Options: descendants `{}`, backlinks `{}`, database views `{}`, task context `{}`, page comments `{}`\n\n",
        options.include_descendants,
        options.include_backlinks,
        options.include_database_views,
        options.include_task_context,
        options.include_page_comments,
    ));

    render_pages(pool, &mut markdown, pages, options, diagnostics).await?;
    render_database_views(&mut markdown, database_views);
    render_projects(&mut markdown, projects);
    render_backlinks(&mut markdown, backlinks);
    if diagnostics.is_empty() {
        markdown.push_str("\n## Diagnostics\n\n- None.\n");
    } else {
        markdown.push_str("\n## Diagnostics\n\n");
        for diagnostic in diagnostics.iter() {
            markdown.push_str(&format!(
                "- `{}` `{}`: {}\n",
                diagnostic.severity,
                diagnostic.code,
                escape_inline(&diagnostic.message)
            ));
        }
    }
    Ok(markdown.trim_end().to_string() + "\n")
}

pub(super) fn csv_to_markdown_table(csv: &str) -> Result<String, String> {
    let rows = parse_csv(csv)?;
    if rows.is_empty() {
        return Ok("_No rows._".to_string());
    }
    let width = rows.iter().map(Vec::len).max().unwrap_or(0);
    if width == 0 {
        return Ok("_No columns._".to_string());
    }
    let mut normalized = rows
        .into_iter()
        .map(|mut row| {
            row.resize(width, String::new());
            row
        })
        .collect::<Vec<_>>();
    if normalized.len() == 1 {
        normalized.push(vec![String::new(); width]);
    }
    let mut lines = Vec::new();
    lines.push(format!(
        "| {} |",
        normalized[0]
            .iter()
            .map(|cell| markdown_table_cell(cell))
            .collect::<Vec<_>>()
            .join(" | ")
    ));
    lines.push(format!(
        "| {} |",
        std::iter::repeat_n("---", width)
            .collect::<Vec<_>>()
            .join(" | ")
    ));
    for row in normalized.iter().skip(1) {
        lines.push(format!(
            "| {} |",
            row.iter()
                .map(|cell| markdown_table_cell(cell))
                .collect::<Vec<_>>()
                .join(" | ")
        ));
    }
    Ok(lines.join("\n"))
}

async fn render_pages(
    pool: &SqlitePool,
    markdown: &mut String,
    pages: &[BridgePage],
    options: BridgeOptions,
    diagnostics: &mut Vec<NoteAgentBridgeExportDiagnosticDto>,
) -> Result<(), String> {
    if pages.is_empty() {
        return Ok(());
    }
    markdown.push_str("## Project knowledge base pages\n\n");
    for page in pages {
        markdown.push_str(&format!(
            "### {}\n\n",
            escape_inline(&display_title(&page.title))
        ));
        markdown.push_str(&format!(
            "Bridge page id: `{}`. Derivative: `true`.\n\n",
            page.id
        ));
        let export = transfers::markdown_export::export_page(
            pool,
            NoteMarkdownExportRequest {
                page_id: page.id.clone(),
                include_page_title: Some(false),
                include_comments: Some(options.include_page_comments),
                include_resolved_comments: Some(
                    options.include_page_comments && options.include_resolved_comments,
                ),
            },
        )
        .await?;
        for diagnostic in export.diagnostics {
            diagnostics.push(NoteAgentBridgeExportDiagnosticDto::new(
                diagnostic.code,
                diagnostic.severity,
                Some("page"),
                Some(page.id.clone()),
                diagnostic.message,
            ));
        }
        if export.markdown.trim().is_empty() {
            markdown.push_str("_Empty page._\n\n");
        } else {
            markdown.push_str(export.markdown.trim());
            markdown.push_str("\n\n");
        }
    }
    Ok(())
}

fn render_database_views(markdown: &mut String, views: &[BridgeDatabaseView]) {
    if views.is_empty() {
        return;
    }
    markdown.push_str("## Database views\n\n");
    for view in views {
        markdown.push_str(&format!(
            "### {}\n\n",
            escape_inline(&display_title(&view.title))
        ));
        markdown.push_str(&format!(
            "- Source page: {}\n- Rows: `{}`\n- Data source id: `{}`\n- Database id: `{}`\n- View id: `{}`\n- Block id: `{}`\n\n",
            escape_inline(&display_title(&view.page_title)),
            view.exported_row_count,
            view.data_source_id,
            view.database_id,
            view.view_id,
            view.block_id,
        ));
        markdown.push_str(&view.markdown_table);
        markdown.push_str("\n\n");
    }
}

fn render_projects(markdown: &mut String, projects: &[BridgeProject]) {
    if projects.is_empty() {
        return;
    }
    markdown.push_str("## Project task context\n\n");
    for project in projects {
        let title = if project.group_name.trim().is_empty() {
            display_title(&project.name)
        } else {
            format!(
                "{} / {}",
                display_title(&project.group_name),
                display_title(&project.name)
            )
        };
        markdown.push_str(&format!("### {}\n\n", escape_inline(&title)));
        markdown.push_str(&format!(
            "- Project id: `{}`\n- Status: `{}`\n- Active tasks: `{}`\n\n",
            project.id,
            project.status,
            project.tasks.len()
        ));
        if project.tasks.is_empty() {
            markdown.push_str("_No active tasks._\n\n");
            continue;
        }
        let mut current_section = String::new();
        for task in &project.tasks {
            if task.section_name != current_section {
                current_section = task.section_name.clone();
                markdown.push_str(&format!(
                    "#### {}\n\n",
                    escape_inline(&display_title(&current_section))
                ));
            }
            let marker = if task.completed_at.is_some() {
                "[x]"
            } else {
                "[ ]"
            };
            markdown.push_str(&format!(
                "- {marker} {} (`{}`)\n",
                escape_inline(&display_title(&task.title)),
                task.id
            ));
            markdown.push_str(&format!(
                "  - Status: `{}`. Priority: `{}`. Type: `{}`.\n",
                escape_inline(&task.status_name),
                escape_inline(&task.priority),
                escape_inline(&task.task_type)
            ));
            if let Some(parent) = &task.parent_title {
                markdown.push_str(&format!("  - Parent: {}\n", escape_inline(parent)));
            }
            let schedule = schedule_text(task);
            if !schedule.is_empty() {
                markdown.push_str(&format!("  - Schedule: {schedule}\n"));
            }
            if let Some(estimate) = task.estimate_minutes {
                markdown.push_str(&format!("  - Estimate: `{estimate}` minutes\n"));
            }
            if !task.tags.is_empty() {
                markdown.push_str(&format!(
                    "  - Tags: {}\n",
                    task.tags
                        .iter()
                        .map(|tag| format!("`{}`", escape_inline(tag)))
                        .collect::<Vec<_>>()
                        .join(", ")
                ));
            }
            if let Some(blocker) = &task.blocker_reason {
                if !blocker.trim().is_empty() {
                    markdown.push_str(&format!("  - Blocker: {}\n", escape_inline(blocker)));
                }
            }
            if !task.description.trim().is_empty() {
                markdown.push_str("  - Description:\n");
                for line in task.description.lines() {
                    markdown.push_str(&format!("    {}\n", escape_inline(line)));
                }
            }
            for item in &task.checklist {
                let marker = if item.completed { "[x]" } else { "[ ]" };
                markdown.push_str(&format!("  - {marker} {}\n", escape_inline(&item.title)));
            }
        }
        markdown.push('\n');
    }
}

fn render_backlinks(markdown: &mut String, backlinks: &[BridgeBacklink]) {
    if backlinks.is_empty() {
        return;
    }
    markdown.push_str("## Backlinks\n\n");
    let mut by_target = BTreeMap::<(&str, &str), Vec<&BridgeBacklink>>::new();
    for backlink in backlinks {
        by_target
            .entry((&backlink.target_title, &backlink.target_id))
            .or_default()
            .push(backlink);
    }
    for ((target_title, target_id), rows) in by_target {
        markdown.push_str(&format!(
            "### {}\n\n",
            escape_inline(&display_title(target_title))
        ));
        markdown.push_str(&format!("Target page id: `{target_id}`\n\n"));
        for row in rows {
            markdown.push_str(&format!(
                "- {} via `{}`",
                escape_inline(&display_title(&row.source_page_title)),
                row.reference_type
            ));
            if let Some(block_id) = &row.source_block_id {
                markdown.push_str(&format!(", block `{block_id}`"));
            }
            if let Some(comment_id) = &row.source_comment_id {
                markdown.push_str(&format!(", comment `{comment_id}`"));
            }
            markdown.push_str(&format!(", source page `{}`", row.source_page_id));
            if !row.snippet.trim().is_empty() {
                markdown.push_str(&format!(": {}", escape_inline(&row.snippet)));
            }
            markdown.push('\n');
        }
        markdown.push('\n');
    }
}

fn schedule_text(task: &BridgeTask) -> String {
    let mut parts = Vec::new();
    if let Some(start) = &task.start_date {
        parts.push(format!("start `{start}`"));
    }
    if let Some(due) = &task.due_date {
        parts.push(format!("due `{due}`"));
    }
    if let Some(target_end) = &task.target_end_date {
        parts.push(format!("target end `{target_end}`"));
    }
    parts.join(", ")
}

fn parse_csv(csv: &str) -> Result<Vec<Vec<String>>, String> {
    let mut rows = Vec::new();
    let mut row = Vec::new();
    let mut cell = String::new();
    let mut chars = csv.chars().peekable();
    let mut quoted = false;
    while let Some(ch) = chars.next() {
        match ch {
            '"' if quoted && chars.peek() == Some(&'"') => {
                chars.next();
                cell.push('"');
            }
            '"' => quoted = !quoted,
            ',' if !quoted => {
                row.push(std::mem::take(&mut cell));
            }
            '\n' if !quoted => {
                row.push(std::mem::take(&mut cell));
                rows.push(std::mem::take(&mut row));
            }
            '\r' if !quoted => {}
            _ => cell.push(ch),
        }
    }
    if quoted {
        return Err("CSV export contained an unterminated quoted cell".to_string());
    }
    if !cell.is_empty() || !row.is_empty() {
        row.push(cell);
        rows.push(row);
    }
    Ok(rows)
}

fn markdown_table_cell(value: &str) -> String {
    escape_link_label(value)
        .replace('|', "\\|")
        .replace('\n', "<br>")
}

fn display_title(value: &str) -> String {
    let trimmed = value.trim();
    if trimmed.is_empty() {
        "Untitled".to_string()
    } else {
        trimmed.to_string()
    }
}
